### ISSUE TITLE
Have the proper `installURL`

### ISSUE THREAD

**Issue by brucellino** [EGI-Foundation/bdii#10]
the installURL should point to where we get the RPM from now - probably this repositories' releases page.

**Comment by gwarf** [comment]
@brucellino if we address this issue we can make a release that will already include linting and other goodies.

**Comment by gwarf** [comment]
in #12 I've set a generic URL, it's not possible to have one install_url covering all the needs (multiple OS and versions): https://github.com/EGI-Foundation/bdii/pull/12/files#diff-825c48cfd9d909baadb0f1e3fdee98f1L34

 Feedback?

**Comment by gwarf** [comment]
Closed via #12
