### ISSUE TITLE
Python 3 and OpenLDAP changes

### ISSUE THREAD

**Issue by ellert** [EGI-Foundation/bdii#13]
`bdii-update` is a python 2 script. An issue was recently filed in redhat bugzilla for the bdii package:

https://bugzilla.redhat.com/show_bug.cgi?id=1737909

What are the plans for bdii w.r.t. the EOL of python 2? Does it work with python 3 already?

A second issue that has come up recently is the future of bdb and hdb backends in openldap:

https://fedoraproject.org/wiki/Changes/OpenLDAPwithBerkleyDBasModule

`bdii` uses hdb. The announced change to provide bdb and hdb backends as modules can easily be accommodated. OpenLDAP is already packages this way in Debian, and the Debian bdii package has the necessary changes that can be ported to Fedora.

However, the change proposal also states

> This change is directed to conduct a smoother experience before the backends are removed in a next Fedora release.
> A step on a way to remove unsupported (both by OpenLDAP and BerkleyDB upstream) piece of software. 

The longer term fix is to migrate to the mdb backend. Has this been tested?

**Comment by gwarf** [comment]
Thanks!
We also got a report from Fedora team: https://github.com/EGI-Foundation/glue-validator/issues/2

There is no clear plan on python3 support as of now, probably lots of python scripts in the various BDII packages would have to be tested and updated.
For the MDB backend I've never heard about any test related to this.

As far as I can tell the main target is CentOS 7 (and still some 6) and I'm not sure how those changes may happen in CentOS 7.

BDII is a project with low activity and maintenance effort, but we have to make some clear plans for the coming years to better understand what we should do, so we will discuss this.

**Comment by gwarf** [comment]
So we will most probably move to python3 only, the bdb/hdb stuff will also have to be figured out.

**Comment by gwarf** [comment]
Python 3 is being addressed via #25 so mainly we now miss the ldap-server part.

We had some discussions about LDAP in https://github.com/EGI-Foundation/bdii/pull/15#issuecomment-737162332.

Basically the agreement is to have some openldap-server packaged be either pushed in UMD (@msalle proposed some help here) and @lfield discussed the fact that it would be good to have some openldap-server be pushed to ~LDAP~ EPEL and I feel the same.

@ellert your name have been mentioned, what's your position on this?

**Comment by lfield** [comment]
You mean pushed to EPEL not LDAP?

**Comment by lfield** [comment]
Pushing to EPEL should be easy. As far as I can tell the Fedora build automatically creates the server package.

https://koji.fedoraproject.org/koji/buildinfo?buildID=1645917

So someone would just need to join the package maintainers and kick off a build for EPEL 8.

https://bodhi.fedoraproject.org/updates/?search=openldap

@ellert probably has the highest reputation and would be best placed to do this

**Comment by msalle** [comment]
Just to let you know that rebuilding the e.g. F33 source RPM works fine for CentOS8 and produces also an openldap-servers rpm, see e.g. https://copr.fedorainfracloud.org/coprs/msalle/OpenLDAP/build/1772351/
I think one of the other builds have already been tested by EGI, @gwarf knows that better.

**Comment by gwarf** [comment]
So I think you are referring to @andrea-manzi that made some quick tests in a CentOS 8 container, and it went well but I wouldn't say it was an extensive/real-world like test. Still confirming the feasibility of this.

**Comment by gwarf** [comment]
Since https://github.com/EGI-Foundation/bdii/pull/15 we are using the openldap-servers package from @msalle' COPR to provide the required dependency while installing the package in a GitHub action.
master is currently python3 only, we will make some tests and make some further PR if needed.
@ellert: @andrea-manzi ported your fixes that you created for EPEL8, with the aim of having the same codebase and a similar spec file.
Mattias do you think it would be possible for you to push an openldap-servers package to EPEL8?

**Comment by gwarf** [comment]
I think that with the merge of #42 for migrating to MDB (and there was #25 for python 3) we can finally close this, thanks!
