### ISSUE TITLE
CentOS8 support

### ISSUE THREAD

**Issue by vokac** [EGI-Foundation/bdii#18]
What is the status of CentOS8 support?

**Comment by gwarf** [comment]
I think it wasn't tested, and probably not working, at least for the python scripts that have not all been ported to python3. Unfortunately BDII is currently missing some love/time... 
Are you in need for CentOS8 support, or is this just hypothetical?

**Comment by vokac** [comment]
RedHat 8 was released a year ago and now we already have 8.2 ... it is time to start supporting new OS within grid software including components that publishes BDII data. Currently BDII server is missing so the only option is to get working server soon or drop support for publishing BDII data (e.g. data published for storages are not really used within WLCG and it should be relatively safe not to support BDII for these purposes).

Currently python doesn't seems to me as most important question, because CentOS8 doesn't even provide openldap server used by BDII service. Are you planning to use different LDAP server implementation?

**Comment by gwarf** [comment]
Indeed the LDAP part is another problem, it was also reported in #13.
Other services may probably not already be compatible with CentOS 8, but it's indeed starting to move a bit on that side, as an example: https://wiki.egi.eu/wiki/Next_middleware_release
So things need to start moving forward, but I'm not aware of any clear plans yet. Things are quite static here, but we will discuss this with the operations team to see what we can be planned.

**Comment by vokac** [comment]
#13 mentions only missing openldap server backends, but CentOS8 doesn't compile/distribute openldap server at all, only openldap client is still available.

It's nice there are plans to move forward with packages for CenOS8 although personally I don't really like when UMD duplicate packages that are already available in the EPEL (sometimes this lead to conflict / unresolved dependencies). On the other hand in future containerized world package repositories / distribution will be much less important.

**Comment by gwarf** [comment]
Situation with regards OpenLDAP clearly will have to be discussed to see what is the best approach.
The goal of UMD is to provide a repository with curated/tested software having gone through stage rollout and automated testing to help detect problems that could affect the infrastructure so yes it could mean some duplication (and delay).

**Comment by gwarf** [comment]
Python 3 support is being addressed by #25, we are discussing openldap-server in #13, please follow the discussions there.

But basically the intent is to release for CentOS 8 once we will have this two points properly covered.
