### ISSUE TITLE
BDII_HOSTNAME hardcoded to 'localhost'

### ISSUE THREAD

**Issue by drebatto** [EGI-Foundation/bdii#19]
Hi,
for some reason that I still have to investigate, the slapd daemon as configured by CERNOps_bdii Puppet module does not accept connections on the 'lo' interface.
As a workaround, I tried to specify ```BDII_HOSTNAME``` in ```/etc/bdii/bdii-update.conf```, but I found out that the value is overwritten in ```/usr/sbin/bdii-update``` (see [here](https://github.com/EGI-Foundation/bdii/blob/c53551649ea0ef26a39a159f86323a3cb63614a9/bin/bdii-update#L159)).
Is there a reason for not using 'localhost' just as a default value?

Cheers,
David

**Comment by gwarf** [comment]
This should be fixed by #22, thanks for the report David!
