### ISSUE TITLE
The init script start should not fail on stale PID

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/bdii#3]
Currently if the BDII process is killed/crashed it leaves a PID fil and this PID file prevents the start function to succeed. The use of the restart argument is needed.

So the init script startup sequeence should look for and delete any stale PID and start the process correctly.
It was reported in the following GGUS ticket: https://ggus.eu/index.php?mode=ticket_info&ticket_id=128120

**Comment by pandreetto** [comment]
I've prepared a pull request with a tentative fix.
I have some doubts about the lock files, expecially regarding the master lock /var/lock/subsys/bdii.
Is it necessary?

**Comment by gwarf** [comment]
Hi @pandreetto, thanks for the PR.
Indeed I don't really understand what is the goal of the `lockfile` lock here, it's created in `start` and deleted in `stop`, but not used anywhere else... May it be checked by some other external components? (would be weird...)

**Comment by gwarf** [comment]
So reading more I think the lockfile is probably here to be read by the system when doing a shutdown to avoid trying to stop services that are not running, or starting services that are already running. In that case I would expect to have some logic somewhere checking it when doing the start and to remove it if it's stale, maybe on some system init is doing this, I will search to verify that and find recommended/usual ways of doing this.
This init scipt seems overly complex...

**Comment by gwarf** [comment]
Should be fixed with #5
