### ISSUE TITLE
Bdii and openldap 2.5+

### ISSUE THREAD

**Issue by ellert** [EGI-Foundation/bdii#41]
# Short Description of the issue

Openldap 2.5 has dropped the bdb and hdb backends that bdii is using.

## Environment

- Operating System: Fedora 36 has openldap 2.6, Debian testing/unstable has openldap 2.5

# Summary of proposed changes

The migration guide for openldap 2.5 suggest users of the bdb and hbd backends to migrate to the mdb backend.

https://www.openldap.org/doc/admin25/appendix-upgrading.html

**Comment by gwarf** [comment]
Closed by #42, thanks!
