### ISSUE TITLE
bdii-update uses obsolete -h and -p flag

### ISSUE THREAD

**Issue by nsc-jens** [EGI-Foundation/bdii#49]
I am trying to use bdii 5.2.26-2 (and 6.0.0-1) on Ubuntu  22.04. The packages installs but the bdii-update script uses the flags" -h HOST" and "-p PORT"  instead of the "-H URI" flag. These flags are removed in OpenLDAP 2.5 according to this page:

https://openldap.org/doc/admin25/appendix-upgrading.html

So the provider works and the BDII slapd is running but bdii-update can't insert data into it.

# Summary of proposed changes

Update bdii-update to use -H URI instead of removed flags.

**Comment by gwarf** [comment]
Dear Jens, thanks for the report, and sorry for the lack of response.
Did you have the opportunity to patch this and test this on your own?
Would you be able/willing to submit a PR?

**Comment by brucellino** [comment]
hi @nsc-jens Thanks for this - I'll have a look. Can you provide me with some evidence of an error? 

@EGI-Federation/bdii are we going to keep backward-compatibility with <2.5 ?

**Comment by gwarf** [comment]
From quick checks, I feel like replacing by -H may not be breaking compatibility, as an example for ldapadd 2.2, we should alrady have the -H option
https://www.openldap.org/software/man.cgi?query=ldapadd&apropos=0&sektion=1&manpath=OpenLDAP+2.2-Release&arch=default&format=html

**Comment by brucellino** [comment]
We should test it then. We can use a standard runner (no container).

**Comment by gwarf** [comment]
In case no one can make a PR for this one, I will do it by next Friday and then release a new BDII version.

**Comment by gwarf** [comment]
Dear @nsc-jens, a new version for AlmaLinux 9 got released, would be great if you could give it a test and report: https://github.com/EGI-Federation/bdii/releases/tag/v6.0.2
Thanks!

**Comment by nsc-jens** [comment]
Den 2024-06-17 kl. 09:11, skrev Baptiste Grenier:
> Dear @nsc-jens <https://github.com/nsc-jens>, a new version for 
> AlmaLinux 9 got released, would be great if you could give it a test and 
> report: https://github.com/EGI-Federation/bdii/releases/tag/v6.0.2 
> <https://github.com/EGI-Federation/bdii/releases/tag/v6.0.2>
> Thanks!

Excellent timing. I was going to upgrade my site-bdii to Rocky 9 
tomorrow so this fits perfectly.

/jens
