### ISSUE TITLE
bdii-slapd-start breaks when BDII_IPV6_SUPPORT=yes

### ISSUE THREAD

**Issue by zsalvet** [EGI-Foundation/bdii#50]
# Short Description of the issue
bdii-slapd-start tries to execute slapd with incorrectly quoted arguments when BDII_IPV6_SUPPORT=yes is set in /etc/bdii/bdii.conf due to unsuitable expansion of SLAPD_HOST_STRING variable.

## Environment

- Operating System:
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes
This can be fixed by replacing the last command
    exec ${COMMAND}
with 
   exec ${SLAPD} -f ${SLAPD_CONF} -h "${SLAPD_HOST_STRING}" -u ${BDII_USER}

**Comment by marianne013** [comment]
Is there an ETA for when this will be fixed ? It's such a small fix....

**Comment by gwarf** [comment]
Sorry for the delay in managing this, we had some available time/effort issue for this.
@brucellino will kindly help to look into this, thanks!

**Comment by brucellino** [comment]
Thanks @gwarf - We have a PR ready, it needs to be tested though. I'll work on this and get back in a few days. @marianne013 @zsalvet if you have any relevant updates, please let us know here :)
